### ISSUE TITLE
TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by rumenandreev01** [Luke-Wilson/basic-react-timepicker#1]
Hey,

when trying to run the app i get the issue below:

![1](https://user-images.githubusercontent.com/20254614/50909586-d5d6f480-1434-11e9-902a-286b005a2882.PNG)
![2](https://user-images.githubusercontent.com/20254614/50909614-e0918980-1434-11e9-86e1-63c7ede03877.PNG)

**Comment by Luke-Wilson** [comment]
Sorry @rumenandreev01 - For some reason I didn't get a notification for this. 

I realise that you've likely moved on from this, but for anyone else that runs into this, this error is telling you that on line 14, `React.PropTypes` is undefined. 

It's probably because since React 15.5, it doesn't ship with PropTypes. You can read more [here](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html)

I'll need to fix this. Sorry!

**Comment by srikanthpathlavath** [comment]
how to import this package in es6 or 7?

**Comment by ertemishakk** [comment]
The problem still exists as of now.

**Comment by itschrislow** [comment]
Facing the same problem...

**Comment by greghesp** [comment]
Same issue here

**Comment by darklight147** [comment]
2021, same issue

**Comment by Luke-Wilson** [comment]
Apologies all - I have now deprecated this package and will not be making any future changes, as I would rather start from scratch than try to refactor this. 

CC: @darklight147 

(Edited to clarify my comment)

**Comment by darklight147** [comment]
Good luuck 😀
